name: Build EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE
      run: |
        python build.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PriceAnalyzer
        path: dist/PriceAnalyzer.exe
